//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Vaishnavi\Solution_AutoHoleInspector\HoleSelectionUI.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: HP
//              Version: NX 2306
//              Date: 12-29-2025  (Format: mm-dd-yyyy)
//              Time: 13:48 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.Features;
using NXOpen.UF;
using NXOpen.Utilities;
using NXOpen.VectorArithmetic;
using System;
using static NXOpen.Tooling.ReusablePocketBuilder;



//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class HoleSelectionUI
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;
    private NXOpen.BlockStyler.SelectObject holeOneID;
    private NXOpen.BlockStyler.SelectObject holeTwoID;
    private NXOpen.BlockStyler.SpecifyCSYS csysID;
    private NXOpen.BlockStyler.Group group;// Block type: Group
    private NXOpen.BlockStyler.FolderSelection folderSelectionID;// Block type: NativeFolderBrowser
    private NXOpen.BlockStyler.Button executeID;

    private static UFSession theUfSession = UFSession.GetUFSession();



    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesEnabled_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesEnabled_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesEnabled_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesEnabled_TwocurveIntersection = (1 << 13);
    public static readonly int SnapPointTypesEnabled_TangentPoint = (1 << 14);
    public static readonly int SnapPointTypesEnabled_Poles = (1 << 15);
    public static readonly int SnapPointTypesEnabled_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesEnabled_FacetVertexPoint = (1 << 17);
    public static readonly int SnapPointTypesEnabled_DefiningPoint = (1 << 18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesOnByDefault_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesOnByDefault_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesOnByDefault_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesOnByDefault_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesOnByDefault_FacetVertexPoint = (1 << 17);

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public HoleSelectionUI()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "HoleSelectionUI.dlx";
            theDialog = theUI.CreateDialog(System.IO.Path.Combine(AppContext.BaseDirectory, theDlxFileName));
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        PartSelection partDlg = null;
        HoleSelectionUI holeDlg = null;

        try
        {
            //partDlg = new PartSelection();
            //NXOpen.BlockStyler.BlockDialog.DialogResponse resp =
            //    partDlg.Launch();

            //partDlg.Dispose();
            //partDlg = null;

            
            //if (resp != NXOpen.BlockStyler.BlockDialog.DialogResponse.Ok)
            //    return;

            
            holeDlg = new HoleSelectionUI();
            holeDlg.Launch();
        }
        catch (Exception ex)
        {
            UI.GetUI().NXMessageBox.Show(
                "Launcher Error",
                NXMessageBox.DialogType.Error,
                ex.ToString()
            );
        }
        finally
        {
            if (holeDlg != null)
                holeDlg.Dispose();
        }
    }

    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
    public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }

    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
            GetUnloadOption(arg);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }

    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            holeOneID = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("holeOneID");
            holeTwoID = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("holeTwoID");
            csysID = (SpecifyCSYS)theDialog.TopBlock.FindBlock("csysID");
            group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
            folderSelectionID = (NXOpen.BlockStyler.FolderSelection)theDialog.TopBlock.FindBlock("folderSelectionID");
            executeID = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("executeID");


            // ===============================
            // FILTER FOR DATUM HOLE 1
            // ===============================
            holeOneID.ClearFilter();

            NXOpen.Selection.MaskTriple circularEdgeMask =
                new NXOpen.Selection.MaskTriple(
                    UFConstants.UF_solid_type,
                    0,
                    UFConstants.UF_UI_SEL_FEATURE_CIRCULAR_EDGE
                );

            holeOneID.SetSelectionFilter(
                NXOpen.Selection.SelectionAction.ClearAndEnableSpecific,
                new NXOpen.Selection.MaskTriple[] { circularEdgeMask }
            );

            holeOneID.MaximumScopeAsString = "Entire Assembly";

            // ===============================
            // FILTER FOR DATUM HOLE 2
            // ===============================
            holeTwoID.ClearFilter();

            holeTwoID.SetSelectionFilter(
                NXOpen.Selection.SelectionAction.ClearAndEnableSpecific,
                new NXOpen.Selection.MaskTriple[] { circularEdgeMask }
            );

            holeTwoID.MaximumScopeAsString = "Entire Assembly";
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString()
            );
        }
    }


    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set
    //here will take precedence and dialog will be launched showing that value.
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if (block == holeOneID)
            {
                //---------Enter your code here-----------
            }
            else if (block == holeTwoID)
            {
                //---------Enter your code here-----------
            }
            else if (block == csysID)
            {
                //---------Enter your code here-----------
            }
            else if (block == folderSelectionID)
            {
                //---------Enter your code here-----------
            }
            else if (block == executeID)
            {
                //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        try
        {


            Edge hole1 = GetSelectedHoleEdge(holeOneID, "Datum Hole 1");
            Edge hole2 = GetSelectedHoleEdge(holeTwoID, "Datum Hole 2");

            double dia1 = GetDiameterFromCircularEdge(hole1);
            double dia2 = GetDiameterFromCircularEdge(hole2);
            CartesianCoordinateSystem carCsys = GetUserDefinedCsys();

            GetUserCsysData(
                carCsys,
                out Point3d origin,
                out Vector3d xDir,
                out Vector3d yDir,
                out Vector3d zDir
            );

            Point3d c1 = GetHoleCenterFromEdge(hole1);
            Point3d c2 = GetHoleCenterFromEdge(hole2);

            // pitch (CORRECT)
            double pitch = GetPitchAlongAxis(c1, c2, yDir);

            // transform points
            Point3d h1Local = TransformToUserCsys(c1, origin, xDir, yDir, zDir);
            Point3d h2Local = TransformToUserCsys(c2, origin, xDir, yDir, zDir);

            // mutual angle (CORRECT)
            double mutualAngle = MutualAngleAroundCarLine(h1Local, h2Local);





            // ----------------------------------------
            // 8. Result output
            // ----------------------------------------
            theUI.NXMessageBox.Show(
                "Hole Angle Analysis (ZX Plane)",
                NXMessageBox.DialogType.Information,
                $"Datum Hole 1 Diameter = {dia1:F3} mm\n" +
                $"Datum Hole 2 Diameter = {dia2:F3} mm\n\n"+
                $"Pitch Distance = {pitch:F3} mm\n\n" +
                $"Hole-1 Center : X={c1.X:F3}, Y={c1.Y:F3}, Z={c1.Z:F3}\n" +                
                $"Hole-2 Center : X={c2.X:F3}, Y={c2.Y:F3}, Z={c2.Z:F3}\n\n" +
                $"Mutual Hole Angle = {mutualAngle:F3}Â°"
            );

            return 0;




        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Hole Selection Error",
                NXMessageBox.DialogType.Error,
                ex.Message
            );
            return 1;
        }
    }



    //private DatumCsys GetSelectedCsys()
    //{
    //    TaggedObject[] sel = csysID.GetSelectedObjects();

    //    if (sel == null || sel.Length == 0)
    //        throw new Exception("Please select a CAR line CSYS.");

    //    DatumCsys csys = sel[0] as DatumCsys;

    //    if (csys == null)
    //        throw new Exception("Selected object is not a Datum CSYS.");

    //    return csys;
    //}

    private CartesianCoordinateSystem GetUserDefinedCsys()
    {
        TaggedObject[] selected = csysID.GetSelectedObjects();

        if (selected == null || selected.Length == 0)
            throw new Exception("Please select or define CAR line CSYS.");

        // Case 1: User picked a Datum CSYS
        DatumCsys datum = selected[0] as DatumCsys;
        if (datum != null)
        {
            return datum.GetEntities()[0] as CartesianCoordinateSystem;
        }

        // Case 2: User picked an existing CSYS directly
        CartesianCoordinateSystem csys = selected[0] as CartesianCoordinateSystem;
        if (csys != null)
        {
            return csys;
        }

        throw new Exception("Selected object is not a valid CSYS.");
    }



    private void GetUserCsysData(
    CartesianCoordinateSystem csys,
    out Point3d origin,
    out Vector3d xDir,
    out Vector3d yDir,
    out Vector3d zDir)
    {
        origin = csys.Origin;
        Matrix3x3 m = csys.Orientation.Element;

        xDir = Normalize(new Vector3d(m.Xx, m.Xy, m.Xz));
        yDir = Normalize(new Vector3d(m.Yx, m.Yy, m.Yz));
        zDir = Normalize(new Vector3d(m.Zx, m.Zy, m.Zz)); // CAR line
    }

    private Vector3d Normalize(Vector3d v)
    {
        double mag = Math.Sqrt(v.X * v.X + v.Y * v.Y + v.Z * v.Z);
        return new Vector3d(v.X / mag, v.Y / mag, v.Z / mag);
    }



    private Edge GetSelectedHoleEdge(NXOpen.BlockStyler.SelectObject holeBlock, string holeName)

    {
        TaggedObject[] selectedObjects = holeBlock.GetSelectedObjects();

        if (selectedObjects == null || selectedObjects.Length == 0)
            throw new Exception($"Please select {holeName}.");

        Edge edge = selectedObjects[0] as Edge;

        if (edge == null)
            throw new Exception($"{holeName} is not a circular edge.");

        return edge;
    }

    private double GetDiameterFromCircularEdge(Edge edge)
    {
        Part workPart = theSession.Parts.Work;

        Unit mmUnit = workPart.UnitCollection.FindObject("MilliMeter") as Unit;

        NXObject[] sellist = new NXObject[] { edge };

        bool isApproximate;
        double arcLength;
        double radius;
        double diameter;
        double minRadius;
        Point3d startPoint;
        Point3d endPoint;
        Point3d arcCenter;

        theSession.Measurement.GetArcAndCurveProperties(
            sellist,
            mmUnit,
            true,
            out isApproximate,
            out arcLength,
            out radius,
            out diameter,
            out minRadius,
            out startPoint,
            out endPoint,
            out arcCenter
        );

        return diameter;
    }

    //Finding Pitch Distance

    private double GetPitchAlongAxis(Point3d c1, Point3d c2, Vector3d axis)
    {
        double mag = Math.Sqrt(axis.X * axis.X + axis.Y * axis.Y + axis.Z * axis.Z);
        Vector3d unit = new Vector3d(axis.X / mag, axis.Y / mag, axis.Z / mag);

        Vector3d diff = new Vector3d(
            c2.X - c1.X,
            c2.Y - c1.Y,
            c2.Z - c1.Z
        );

        return Math.Abs(
            diff.X * unit.X +
            diff.Y * unit.Y +
            diff.Z * unit.Z
        );
    }






    // ======================================================
    // STEP 1: Get CSYS origin and Z direction using UFSession
    // ======================================================
    private void GetCsysOriginAndZDirection(
    DatumCsys datumCsys,
    out Point3d origin,
    out Vector3d zDir)
    {
        // Get underlying coordinate system
        CartesianCoordinateSystem csys =
            datumCsys.GetEntities()[0] as CartesianCoordinateSystem;

        if (csys == null)
            throw new Exception("Invalid Datum CSYS selection");

        origin = csys.Origin;

        Matrix3x3 m = csys.Orientation.Element;

        // Z-axis = CAR line
        zDir = new Vector3d(
            m.Zx,
            m.Zy,
            m.Zz
        );
    }

    // ======================================================
    // Get hole center X,Y,Z with respect to user-selected CSYS
    // ======================================================
    private Point3d GetPointInUserCsys(
        Point3d worldPoint,
        DatumCsys datumCsys)
    {
        // Get underlying coordinate system
        CartesianCoordinateSystem csys =
            datumCsys.GetEntities()[0] as CartesianCoordinateSystem;

        if (csys == null)
            throw new Exception("Invalid Datum CSYS");

        // CSYS origin
        Point3d o = csys.Origin;

        // CSYS orientation
        Matrix3x3 m = csys.Orientation.Element;

        Vector3d xAxis = new Vector3d(m.Xx, m.Xy, m.Xz);
        Vector3d yAxis = new Vector3d(m.Yx, m.Yy, m.Yz);
        Vector3d zAxis = new Vector3d(m.Zx, m.Zy, m.Zz); // CAR line

        // Vector from CSYS origin to point
        Vector3d v = new Vector3d(
            worldPoint.X - o.X,
            worldPoint.Y - o.Y,
            worldPoint.Z - o.Z
        );

        // Projection onto CSYS axes
        double x = v.X * xAxis.X + v.Y * xAxis.Y + v.Z * xAxis.Z;
        double y = v.X * yAxis.X + v.Y * yAxis.Y + v.Z * yAxis.Z;
        double z = v.X * zAxis.X + v.Y * zAxis.Y + v.Z * zAxis.Z;

        return new Point3d(x, y, z);
    }

    private double AngleWithCarLine(
    Vector3d vec,
    Vector3d carDir)
    {
        double dot =
            vec.X * carDir.X +
            vec.Y * carDir.Y +
            vec.Z * carDir.Z;

        double magV = Math.Sqrt(
            vec.X * vec.X +
            vec.Y * vec.Y +
            vec.Z * vec.Z);

        double magC = Math.Sqrt(
            carDir.X * carDir.X +
            carDir.Y * carDir.Y +
            carDir.Z * carDir.Z);

        double cosTheta = dot / (magV * magC);

        // Clamp safety
        cosTheta = Math.Max(-1.0, Math.Min(1.0, cosTheta));

        return Math.Acos(cosTheta) * 180.0 / Math.PI;
    }

    private Point3d TransformToUserCsys(
     Point3d worldPoint,
     Point3d origin,
     Vector3d xDir,
     Vector3d yDir,
     Vector3d zDir)
    {
        Vector3d d = new Vector3d(
            worldPoint.X - origin.X,
            worldPoint.Y - origin.Y,
            worldPoint.Z - origin.Z
        );

        return new Point3d(
            Dot(d, xDir),
            Dot(d, yDir),
            Dot(d, zDir)
        );
    }

    private double Dot(Vector3d a, Vector3d b)
    {
        return a.X * b.X + a.Y * b.Y + a.Z * b.Z;
    }


    private double MutualAngleAroundCarLine(
     Point3d h1Local,
     Point3d h2Local)
    {
        // vectors in CAR XY plane
        Vector3d v1 = new Vector3d(h1Local.X, h1Local.Y, 0.0);
        Vector3d v2 = new Vector3d(h2Local.X, h2Local.Y, 0.0);

        double mag1 = Math.Sqrt(v1.X * v1.X + v1.Y * v1.Y);
        double mag2 = Math.Sqrt(v2.X * v2.X + v2.Y * v2.Y);

        if (mag1 < 1e-6 || mag2 < 1e-6)
            return 0.0;

        double cos =
            (v1.X * v2.X + v1.Y * v2.Y) / (mag1 * mag2);

        cos = Math.Max(-1.0, Math.Min(1.0, cos));

        return Math.Acos(cos) * 180.0 / Math.PI;
    }




    private Face GetCylindricalFaceFromEdge(Edge edge)
    {
        foreach (Face face in edge.GetFaces())
        {
            if (face.SolidFaceType == Face.FaceType.Cylindrical)
                return face;
        }

        throw new Exception("No cylindrical face found for this edge");
    }





    private Point3d GetHoleCenterFromEdge(Edge edge)
    {
        Part workPart = theSession.Parts.Work;
        Unit mmUnit = workPart.UnitCollection.FindObject("MilliMeter") as Unit;

        NXObject[] sel = new NXObject[] { edge };

        bool isApproximate;
        double arcLength;
        double radius;
        double diameter;
        double minRadius;
        Point3d startPoint;
        Point3d endPoint;
        Point3d arcCenter;

        theSession.Measurement.GetArcAndCurveProperties(
            sel,
            mmUnit,
            true,
            out isApproximate,
            out arcLength,
            out radius,
            out diameter,
            out minRadius,
            out startPoint,
            out endPoint,
            out arcCenter
        );

        return arcCenter;
    }

    private Vector3d GetHoleAxisFromEdge(Edge edge)
    {
        foreach (Face face in edge.GetFaces())
        {
            if (face.SolidFaceType == Face.FaceType.Cylindrical)
            {
                UFSession uf = UFSession.GetUFSession();

                double[] origin = new double[3];
                double[] axis = new double[3];
                double[] radData = new double[6];
                int type;

                uf.Modl.AskFaceData(
                    face.Tag,
                    out type,
                    origin,
                    axis,
                    radData,
                    out _,
                    out _,
                    out _
                );

                return new Vector3d(axis[0], axis[1], axis[2]);
            }
        }
        throw new Exception("Cylindrical face not found");
    }



    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

}
